#!/usr/bin/env bash
# Slightly tweaked version of https://github.com/evanriley/fuzzel-emoji
set -euo pipefail

EMOJI="$(sed '1,/^### DATA ###$/d' $0 | fuzzel --dmenu --prompt="󰞅 " --match-mode=exact --width=48 | cut -d ' ' -f 1 | tr -d '\n')"
wtype "$EMOJI"; wl-copy "$EMOJI"
exit
### DATA ###
😀 grinning face
😁 beaming face with smiling eyes
😂 face with tears of joy
🤣 rolling on the floor laughing
😃 grinning face with big eyes
😄 grinning face with smiling eyes
😅 grinning face with sweat
😆 grinning squinting face
😉 winking face
😊 smiling face with smiling eyes
😋 face savoring food
😎 smiling face with sunglasses
😍 smiling face with heart-eyes
😘 face blowing a kiss
😗 kissing face
😙 kissing face with smiling eyes
😚 kissing face with closed eyes
☺️ smiling face
🙂 slightly smiling face
🤗 hugging face
🤩 star-struck
🤔 thinking face
🤨 face with raised eyebrow
😐 neutral face
😑 expressionless face
😶 face without mouth
🙄 face with rolling eyes
😏 smirking face
😣 persevering face
😥 sad but relieved face
😮 face with open mouth
🤐 zipper-mouth face
😯 hushed face
😪 sleepy face
😫 tired face
😴 sleeping face
😌 relieved face
😛 face with tongue
😜 winking face with tongue
😝 squinting face with tongue
🤤 drooling face
😒 unamused face
😓 downcast face with sweat
😔 pensive face
😕 confused face
🙃 upside-down face
🤑 money-mouth face
😲 astonished face
☹️ frowning face
🙁 slightly frowning face
😖 confounded face
😞 disappointed face
😟 worried face
😤 face with steam from nose
😢 crying face
😭 loudly crying face
😦 frowning face with open mouth
😧 anguished face
😨 fearful face
😩 weary face
🤯 exploding head
😬 grimacing face
😰 anxious face with sweat
😱 face screaming in fear
🥵 hot face
🥶 cold face
😳 flushed face
🤪 zany face
😵 dizzy face
🥴 woozy face
😠 angry face
😡 pouting face
🤬 face with symbols on mouth
😷 face with medical mask
🤒 face with thermometer
🤕 face with head-bandage
🤢 nauseated face
🤮 face vomiting
🤧 sneezing face
😇 smiling face with halo
🥳 partying face
🥺 pleading face
🤠 cowboy hat face
🤡 clown face
🤥 lying face
🤫 shushing face
🤭 face with hand over mouth
🧐 face with monocle
🤓 nerd face
😈 smiling face with horns
👿 angry face with horns
👹 ogre
👺 goblin
💀 skull
☠️ skull and crossbones
👻 ghost
👽 alien
👾 alien monster
🤖 robot
💩 pile of poo
😺 grinning cat
😸 grinning cat with smiling eyes
😹 cat with tears of joy
😻 smiling cat with heart-eyes
😼 cat with wry smile
😽 kissing cat
🙀 weary cat
😿 crying cat
😾 pouting cat
🙈 see-no-evil monkey
🙉 hear-no-evil monkey
🙊 speak-no-evil monkey
💋 kiss mark
💌 love letter
💘 heart with arrow
💝 heart with ribbon
💖 sparkling heart
💗 growing heart
💓 beating heart
💞 revolving hearts
💕 two hearts
💟 heart decoration
❣️ heavy heart exclamation
💔 broken heart
❤️ red heart
🧡 orange heart
💛 yellow heart
💚 green heart
💙 blue heart
💜 purple heart
🖤 black heart
🤍 white heart
🤎 brown heart
💯 hundred points
💢 anger symbol
💥 collision
💫 dizzy
💦 sweat droplets
💨 dashing away
🕳️ hole
💣 bomb
💬 speech balloon
👁️‍🗨️ eye in speech bubble
🗨️ left speech bubble
🗯️ right anger bubble
💭 thought balloon
💤 zzz
👋 waving hand
🤚 raised back of hand
🖐️ hand with fingers splayed
✋ raised hand
🖖 vulcan salute
👌 ok hand
🤌 pinched fingers
🤏 pinching hand
✌️ victory hand
🤞 crossed fingers
🤟 love-you gesture
🤘 sign of the horns
🤙 call me hand
👈 backhand index pointing left
👉 backhand index pointing right
👆 backhand index pointing up
🖕 middle finger
👇 backhand index pointing down
☝️ index pointing up
👍 thumbs up
👎 thumbs down
✊ raised fist
👊 oncoming fist
🤛 left-facing fist
🤜 right-facing fist
👏 clapping hands
🙌 raising hands
👐 open hands
🤲 palms up together
🤝 handshake
🙏 folded hands
✍️ writing hand
💅 nail polish
🤳 selfie
💪 flexed biceps
🦾 mechanical arm
🦿 mechanical leg
🦵 leg
🦶 foot
👂 ear
🦻 ear with hearing aid
👃 nose
🧠 brain
🫀 anatomical heart
🫁 lungs
🦷 tooth
🦴 bone
👀 eyes
👁️ eye
👅 tongue
👄 mouth
👶 baby
🧒 child
👦 boy
👧 girl
🧑 person
👱 person: blond hair
👨 man
🧔 man: beard
👩 woman
🧓 older person
👴 old man
👵 old woman
🙍 person frowning
🙎 person pouting
🙅 person gesturing no
🙆 person gesturing ok
💁 person tipping hand
🙋 person raising hand
🧏 deaf person
🙇 person bowing
🤦 person facepalming
🤷 person shrugging
👮 police officer
🕵️ detective
💂 guard
🥷 ninja
👷 construction worker
🤴 prince
👸 princess
👳 person wearing turban
👲 person with skullcap
🧕 woman with headscarf
🤵 person in tuxedo
👰 person with veil
🤰 pregnant woman
🤱 breast-feeding
👼 baby angel
🎅 santa claus
🤶 mrs. claus
🦸 superhero
🦹 supervillain
🧙 mage
🧚 fairy
🧛 vampire
🧜 merperson
🧝 elf
🧞 genie
🧟 zombie
💆 person getting massage
💇 person getting haircut
🚶 person walking
🧍 person standing
🧎 person kneeling
🏃 person running
💃 woman dancing
🕺 man dancing
🕴️ person in suit levitating
👯 people with bunny ears
🧖 person in steamy room
🧗 person climbing
🤺 person fencing
🏇 horse racing
⛷️ skier
🏂 snowboarder
🏌️ person golfing
🏄 person surfing
🚣 person rowing boat
🏊 person swimming
⛹️ person bouncing ball
🏋️ person lifting weights
🚴 person biking
🚵 person mountain biking
🤸 person cartwheeling
🤼 people wrestling
🤽 person playing water polo
🤾 person playing handball
🤹 person juggling
🧘 person in lotus position
🛀 person taking bath
🛌 person in bed
👭 women holding hands
👫 woman and man holding hands
👬 men holding hands
💏 kiss
💑 couple with heart
👪 family
👨‍👩‍👧 family: man, woman, girl
👨‍👩‍👧‍👦 family: man, woman, girl, boy
👨‍👩‍👦‍👦 family: man, woman, boy, boy
👨‍👩‍👧‍👧 family: man, woman, girl, girl
👨‍👨‍👦 family: man, man, boy
👨‍👨‍👧 family: man, man, girl
👨‍👨‍👧‍👦 family: man, man, girl, boy
👨‍👨‍👦‍👦 family: man, man, boy, boy
👨‍👨‍👧‍👧 family: man, man, girl, girl
👩‍👩‍👦 family: woman, woman, boy
👩‍👩‍👧 family: woman, woman, girl
👩‍👩‍👧‍👦 family: woman, woman, girl, boy
👩‍👩‍👦‍👦 family: woman, woman, boy, boy
👩‍👩‍👧‍👧 family: woman, woman, girl, girl
👨‍👦 family: man, boy
👨‍👦‍👦 family: man, boy, boy
👨‍👧 family: man, girl
👨‍👧‍👦 family: man, girl, boy
👨‍👧‍👧 family: man, girl, girl
👩‍👦 family: woman, boy
👩‍👦‍👦 family: woman, boy, boy
👩‍👧 family: woman, girl
👩‍👧‍👦 family: woman, girl, boy
👩‍👧‍👧 family: woman, girl, girl
🗣️ speaking head
👤 bust in silhouette
👥 busts in silhouette
🫂 people hugging
🐵 monkey face
🐒 monkey
🦍 gorilla
🦧 orangutan
🐶 dog face
🐕 dog
🦮 guide dog
🐕‍🦺 service dog
🐩 poodle
🐺 wolf
🦊 fox
🦝 raccoon
🐱 cat face
🐈 cat
🐈‍⬛ black cat
🦁 lion
🐯 tiger face
🐅 tiger
🐆 leopard
🐴 horse face
🐎 horse
🦄 unicorn
🦓 zebra
🦌 deer
🦬 bison
🐮 cow face
🐂 ox
🐃 water buffalo
🐄 cow
🐷 pig face
🐖 pig
🐗 boar
🐽 pig nose
🐏 ram
🐑 ewe
🐐 goat
🐪 camel
🐫 two-hump camel
🦙 llama
🦒 giraffe
🐘 elephant
🦣 mammoth
🦏 rhinoceros
🦛 hippopotamus
🐭 mouse face
🐁 mouse
🐀 rat
🐹 hamster
🐰 rabbit face
🐇 rabbit
🐿️ chipmunk
🦫 beaver
🦔 hedgehog
🦇 bat
🐻 bear
🐻‍❄️ polar bear
🐨 koala
🐼 panda
🦥 sloth
🦦 otter
🦨 skunk
🦘 kangaroo
🦡 badger
🐾 paw prints
🦃 turkey
🐔 chicken
🐓 rooster
🐣 hatching chick
🐤 baby chick
🐥 front-facing baby chick
🐦 bird
🐧 penguin
🕊️ dove
🦅 eagle
🦆 duck
🦢 swan
🦉 owl
🦤 dodo
🪶 feather
🦩 flamingo
🦚 peacock
🦜 parrot
🐸 frog
🐊 crocodile
🐢 turtle
🦎 lizard
🐍 snake
🐲 dragon face
🐉 dragon
🦕 sauropod
🦖 t-rex
🐳 spouting whale
🐋 whale
🐬 dolphin
🦭 seal
🐟 fish
🐠 tropical fish
🐡 blowfish
🦈 shark
🐙 octopus
🐚 spiral shell
🐌 snail
🦋 butterfly
🐛 bug
🐜 ant
🐝 honeybee
🪲 beetle
🐞 lady beetle
🦗 cricket
🪳 cockroach
🕷️ spider
🕸️ spider web
🦂 scorpion
🦟 mosquito
🪰 fly
🪱 worm
🦠 microbe
💐 bouquet
🌸 cherry blossom
💮 white flower
🏵️ rosette
🌹 rose
🥀 wilted flower
🌺 hibiscus
🌻 sunflower
🌼 daisy
🌷 tulip
🌱 seedling
🪴 potted plant
🌲 evergreen tree
🌳 deciduous tree
🌴 palm tree
🌵 cactus
🌾 sheaf of rice
🌿 herb
☘️ shamrock
🍀 four leaf clover
🍁 maple leaf
🍂 fallen leaves
🍃 leaf fluttering in wind
🍇 grapes
🍈 melon
🍉 watermelon
🍊 tangerine
🍋 lemon
🍌 banana
🍍 pineapple
🥭 mango
🍎 red apple
🍏 green apple
🍐 pear
🍑 peach
🍒 cherries
🍓 strawberry
🫐 blueberries
🥝 kiwi fruit
🍅 tomato
🫒 olive
🥥 coconut
🥑 avocado
🍆 eggplant
🥔 potato
🥕 carrot
🌽 ear of corn
🌶️ hot pepper
🫑 bell pepper
🥒 cucumber
🥬 leafy greens
🥦 broccoli
🧄 garlic
🧅 onion
🍄 mushroom
🥜 peanuts
🌰 chestnut
🍞 bread
🥐 croissant
🥖 baguette bread
🫓 flatbread
🥨 pretzel
🥯 bagel
🥞 pancakes
🧇 waffle
🧀 cheese wedge
🍖 meat on bone
🍗 poultry leg
🥩 cut of meat
🥓 bacon
🍔 hamburger
🍟 french fries
🍕 pizza
🌭 hot dog
🥪 sandwich
🌮 taco
🌯 burrito
🫔 tamale
🥙 stuffed flatbread
🧆 falafel
🥚 egg
🍳 cooking
🥘 shallow pan of food
🍲 pot of food
🫕 fondue
🥣 bowl with spoon
🥗 green salad
🍿 popcorn
🧈 butter
🧂 salt
🥫 canned food
🍱 bento box
🍘 rice cracker
🍙 rice ball
🍚 cooked rice
🍛 curry rice
🍜 steaming bowl
🍝 spaghetti
🍠 roasted sweet potato
🍢 oden
🍣 sushi
🍤 fried shrimp
🍥 fish cake with swirl
🥮 moon cake
🍡 dango
🥟 dumpling
🥠 fortune cookie
🥡 takeout box
🍦 soft ice cream
🍧 shaved ice
🍨 ice cream
🍩 doughnut
🍪 cookie
🎂 birthday cake
🍰 shortcake
🧁 cupcake
🥧 pie
🍫 chocolate bar
🍬 candy
🍭 lollipop
🍮 custard
🍯 honey pot
🍼 baby bottle
🥛 glass of milk
☕ hot beverage
🫖 teapot
🍵 teacup without handle
🍶 sake
🍾 bottle with popping cork
🍷 wine glass
🍸 cocktail glass
🍹 tropical drink
🍺 beer mug
🍻 clinking beer mugs
🥂 clinking glasses
🥃 tumbler glass
🥤 cup with straw
🧋 bubble tea
🧃 beverage box
🧉 mate
🧊 ice
🥢 chopsticks
🍽️ fork and knife with plate
🍴 fork and knife
🥄 spoon
🔪 kitchen knife
🏺 amphora
🌍 globe showing europe-africa
🌎 globe showing americas
🌏 globe showing asia-australia
🌐 globe with meridians
🗺️ world map
🗾 map of japan
🧭 compass
🏔️ snow-capped mountain
⛰️ mountain
🌋 volcano
🗻 mount fuji
🏕️ camping
🏖️ beach with umbrella
🏜️ desert
🏝️ desert island
🏞️ national park
🏟️ stadium
🏛️ classical building
🏗️ building construction
🧱 brick
🪨 rock
🪵 wood
🛖 hut
🏘️ houses
🏚️ derelict house
🏠 house
🏡 house with garden
🏢 office building
🏣 japanese post office
🏤 post office
🏥 hospital
🏦 bank
🏨 hotel
🏩 love hotel
🏪 convenience store
🏫 school
🏬 department store
🏭 factory
🏯 japanese castle
🏰 castle
💒 wedding
🗼 tokyo tower
🗽 statue of liberty
⛪ church
🕌 mosque
🛕 hindu temple
🕍 synagogue
⛩️ shinto shrine
🕋 kaaba
⛲ fountain
⛺ tent
🌁 foggy
🌃 night with stars
🏙️ cityscape
🌄 sunrise over mountains
🌅 sunrise
🌆 cityscape at dusk
🌇 sunset
🌉 bridge at night
♨️ hot springs
🎠 carousel horse
🎡 ferris wheel
🎢 roller coaster
💈 barber pole
🎪 circus tent
🚂 locomotive
🚃 railway car
🚄 high-speed train
🚅 bullet train
🚆 train
🚇 metro
🚈 light rail
🚉 station
🚊 tram
🚝 monorail
🚞 mountain railway
🚋 tram car
🚌 bus
🚍 oncoming bus
🚎 trolleybus
🚐 minibus
🚑 ambulance
🚒 fire engine
🚓 police car
🚔 oncoming police car
🚕 taxi
🚖 oncoming taxi
🚗 automobile
🚘 oncoming automobile
🚙 sport utility vehicle
🛻 pickup truck
🚚 delivery truck
🚛 articulated lorry
🚜 tractor
🏎️ racing car
🏍️ motorcycle
🛵 motor scooter
🦽 manual wheelchair
🦼 motorized wheelchair
🛴 kick scooter
🚲 bicycle
🛺 auto rickshaw
🚁 helicopter
🚟 suspension railway
🚠 mountain cableway
🚡 aerial tramway
🛰️ satellite
🚀 rocket
🛸 flying saucer
🛎️ bellhop bell
🧳 luggage
⌛ hourglass done
⏳ hourglass not done
⌚ watch
⏰ alarm clock
⏱️ stopwatch
⏲️ timer clock
🕰️ mantelpiece clock
🕛 twelve o'clock
🕧 twelve-thirty
🕐 one o'clock
🕜 one-thirty
🕑 two o'clock
🕝 two-thirty
🕒 three o'clock
🕞 three-thirty
🕓 four o'clock
🕟 four-thirty
🕔 five o'clock
🕠 five-thirty
🕕 six o'clock
🕡 six-thirty
🕖 seven o'clock
🕢 seven-thirty
🕗 eight o'clock
🕣 eight-thirty
🕘 nine o'clock
🕤 nine-thirty
🕙 ten o'clock
🕥 ten-thirty
🕚 eleven o'clock
🕦 eleven-thirty
🌑 new moon
🌒 waxing crescent moon
🌓 first quarter moon
🌔 waxing gibbous moon
🌕 full moon
🌖 waning gibbous moon
🌗 last quarter moon
🌘 waning crescent moon
🌙 crescent moon
🌚 new moon face
🌛 first quarter moon face
🌜 last quarter moon face
🌡️ thermometer
☀️ sun
🌝 full moon face
🌞 sun with face
🪐 ringed planet
⭐ star
🌟 glowing star
🌠 shooting star
🌌 milky way
☁️ cloud
⛅ partly cloudy
⛈️ cloud with lightning and rain
🌤️ sun behind small cloud
🌥️ sun behind large cloud
🌦️ sun behind rain cloud
🌧️ cloud with rain
🌨️ cloud with snow
🌩️ cloud with lightning
🌪️ tornado
🌫️ fog
🌬️ wind face
🌀 cyclone
🌈 rainbow
🌂 closed umbrella
☂️ umbrella
☔ umbrella with rain drops
⛱️ umbrella on ground
⚡ high voltage
❄️ snowflake
☃️ snowman
⛄ snowman without snow
☄️ comet
🔥 fire
💧 droplet
🌊 water wave
🎃 jack-o-lantern
🎄 christmas tree
🎆 fireworks
🎇 sparkler
🧨 firecracker
✨ sparkles
🎈 balloon
🎉 party popper
🎊 confetti ball
🎋 tanabata tree
🎍 pine decoration
🎎 japanese dolls
🎏 carp streamer
🎐 wind chime
🎑 moon viewing ceremony
🧧 red envelope
🎀 ribbon
🎁 wrapped gift
🎗️ reminder ribbon
🎟️ admission tickets
🎫 ticket
🎖️ military medal
🏆 trophy
🏅 sports medal
🥇 1st place medal
🥈 2nd place medal
🥉 3rd place medal
⚽ soccer ball
⚾ baseball
🥎 softball
🏀 basketball
🏐 volleyball
🏈 american football
🏉 rugby football
🎾 tennis
🥏 flying disc
🎳 bowling
🏏 cricket game
🏑 field hockey
🏒 ice hockey
🥍 lacrosse
🏓 ping pong
🏸 badminton
🥊 boxing glove
🥋 martial arts uniform
🥅 goal net
⛳ flag in hole
⛸️ ice skate
🎣 fishing pole
🤿 diving mask
🎽 running shirt
🎿 skis
🛷 sled
🥌 curling stone
🎯 direct hit
🪀 yo-yo
🪁 kite
🎱 pool 8 ball
🔮 crystal ball
🪄 magic wand
🧿 nazar amulet
🎮 video game
🕹️ joystick
🎰 slot machine
🎲 game die
🧩 puzzle piece
🧸 teddy bear
🪅 piñata
🪆 nesting dolls
♠️ spade suit
♥️ heart suit
♦️ diamond suit
♣️ club suit
♟️ chess pawn
🃏 joker
🀄 mahjong red dragon
🎴 flower playing cards
🎭 performing arts
🖼️ framed picture
🎨 artist palette
🧵 thread
🪡 sewing needle
🧶 yarn
🪢 knot
👓 glasses
🕶️ sunglasses
🥽 goggles
🥼 lab coat
🦺 safety vest
👔 necktie
👕 t-shirt
👖 jeans
🧣 scarf
🧤 gloves
🧥 coat
🧦 socks
👗 dress
👘 kimono
🥻 sari
🩱 one-piece swimsuit
🩲 briefs
🩳 shorts
👙 bikini
👚 woman's clothes
👛 purse
👜 handbag
👝 clutch bag
🛍️ shopping bags
🎒 backpack
🩴 thong sandal
👞 man's shoe
👟 running shoe
🥾 hiking boot
🥿 flat shoe
👠 high-heeled shoe
👡 woman's sandal
🩰 ballet shoes
👢 woman's boot
👑 crown
👒 woman's hat
🎩 top hat
🎓 graduation cap
🧢 billed cap
🪖 military helmet
⛑️ rescue worker's helmet
📿 prayer beads
💄 lipstick
💍 ring
💎 gem stone
🔇 muted speaker
🔈 speaker low volume
🔉 speaker medium volume
🔊 speaker high volume
📢 loudspeaker
📣 megaphone
📯 postal horn
🔔 bell
🔕 bell with slash
🎼 musical score
🎵 musical note
🎶 musical notes
🎙️ studio microphone
🎚️ level slider
🎛️ control knobs
🎤 microphone
🎧 headphone
📻 radio
🎷 saxophone
🪗 accordion
🎸 guitar
🎹 musical keyboard
🎺 trumpet
🎻 violin
🪕 banjo
🥁 drum
🪘 long drum
📱 mobile phone
📲 mobile phone with arrow
☎️ telephone
📞 telephone receiver
📟 pager
📠 fax machine
🔋 battery
🔌 electric plug
💻 laptop computer
🖥️ desktop computer
🖨️ printer
⌨️ keyboard
🖱️ computer mouse
🖲️ trackball
💽 computer disk
💾 floppy disk
💿 optical disk
📀 dvd
🧮 abacus
🎥 movie camera
🎞️ film frames
📽️ film projector
🎬 clapper board
📺 television
📷 camera
📸 camera with flash
📹 video camera
📼 videocassette
🔍 magnifying glass tilted left
🔎 magnifying glass tilted right
🕯️ candle
💡 light bulb
🔦 flashlight
🏮 red paper lantern
🪔 diya lamp
📔 notebook with decorative cover
📕 closed book
📖 open book
📗 green book
📘 blue book
📙 orange book
📚 books
📓 notebook
📒 ledger
📃 page with curl
📜 scroll
📄 page facing up
📰 newspaper
🗞️ rolled-up newspaper
📑 bookmark tabs
🔖 bookmark
🏷️ label
💰 money bag
🪙 coin
💴 yen banknote
💵 dollar banknote
💶 euro banknote
💷 pound banknote
💸 money with wings
💳 credit card
🧾 receipt
💹 chart increasing with yen
✉️ envelope
📧 e-mail
📨 incoming envelope
📩 envelope with arrow
📤 outbox tray
📥 inbox tray
📦 package
📫 closed mailbox with raised flag
📪 closed mailbox with lowered flag
📬 open mailbox with raised flag
📭 open mailbox with lowered flag
📮 postbox
🗳️ ballot box with ballot
✏️ pencil
✒️ black nib
🖋️ fountain pen
🖊️ pen
🖌️ paintbrush
🖍️ crayon
📝 memo
💼 briefcase
📁 file folder
📂 open file folder
🗂️ card index dividers
📅 calendar
📆 tear-off calendar
🗒️ spiral notepad
🗓️ spiral calendar
📇 card index
📈 chart increasing
📉 chart decreasing
📊 bar chart
📋 clipboard
📌 pushpin
📍 round pushpin
📎 paperclip
🖇️ linked paperclips
📏 straight ruler
📐 triangular ruler
✂️ scissors
🗃️ card file box
🗄️ file cabinet
🗑️ wastebasket
🔒 locked
🔓 unlocked
🔏 locked with pen
🔐 locked with key
🔑 key
🗝️ old key
🔨 hammer
🪓 axe
⛏️ pick
⚒️ hammer and pick
🛠️ hammer and wrench
🗡️ dagger
⚔️ crossed swords
🔫 pistol
🪃 boomerang
🏹 bow and arrow
🛡️ shield
🪚 carpentry saw
🔧 wrench
🪛 screwdriver
🔩 nut and bolt
⚙️ gear
🗜️ clamp
⚖️ balance scale
🦯 white cane
🔗 link
⛓️ chains
🪝 hook
🧰 toolbox
🧲 magnet
🪜 ladder
⚗️ alembic
🧪 test tube
🧫 petri dish
🧬 dna
🔬 microscope
🔭 telescope
📡 satellite antenna
💉 syringe
🩸 drop of blood
💊 pill
🩹 adhesive bandage
🩺 stethoscope
🚪 door
🛗 elevator
🪞 mirror
🪟 window
🛏️ bed
🛋️ couch and lamp
🪑 chair
🚽 toilet
🪠 plunger
🚿 shower
🛁 bathtub
🪤 mouse trap
🪒 razor
🧴 lotion bottle
🧷 safety pin
🧹 broom
🧺 basket
🧻 roll of paper
🪣 bucket
🧼 soap
🪥 toothbrush
🧽 sponge
🧯 fire extinguisher
🛒 shopping cart
🚬 cigarette
⚰️ coffin
🪦 headstone
⚱️ funeral urn
🗿 moai
🪧 placard
🏧 atm sign
🚮 litter in bin sign
🚰 potable water
♿ wheelchair symbol
🚹 men's room
🚺 women's room
🚻 restroom
🚼 baby symbol
🚾 water closet
🛂 passport control
🛃 customs
🛄 baggage claim
🛅 left luggage
⚠️ warning
🚸 children crossing
⛔ no entry
🚫 prohibited
🚳 no bicycles
🚯 no littering
🚱 non-potable water
🚷 no pedestrians
📵 no mobile phones
🔞 no one under eighteen
☢️ radioactive
☣️ biohazard
⬆️ up arrow
↗️ up-right arrow
➡️ right arrow
↘️ down-right arrow
⬇️ down arrow
↙️ down-left arrow
⬅️ left arrow
↖️ up-left arrow
↕️ up-down arrow
↔️ left-right arrow
↩️ right arrow curving left
↪️ left arrow curving right
⤴️ right arrow curving up
⤵️ right arrow curving down
🔃 clockwise vertical arrows
🔄 counterclockwise arrows button
🔙 back arrow
🔚 end arrow
🔛 on! arrow
🔜 soon arrow
🔝 top arrow
🛐 place of worship
⚛️ atom symbol
🕉️ om
✡️ star of david
☸️ wheel of dharma
☯️ yin yang
✝️ latin cross
☦️ orthodox cross
☪️ star and crescent
☮️ peace symbol
🕎 menorah
🔯 dotted six-pointed star
♈ aries
♉ taurus
♊ gemini
♋ cancer
♌ leo
♍ virgo
♎ libra
♏ scorpio
♐ sagittarius
♑ capricorn
♒ aquarius
♓ pisces
⛎ ophiuchus
🔀 shuffle tracks button
🔁 repeat button
🔂 repeat single button
▶️ play button
⏩ fast-forward button
⏭️ next track button
⏯️ play or pause button
◀️ reverse button
⏪ fast reverse button
⏮️ last track button
🔼 upwards button
⏫ fast up button
🔽 downwards button
⏬ fast down button
⏸️ pause button
⏹️ stop button
⏺️ record button
⏏️ eject button
🎦 cinema
🔅 dim button
🔆 bright button
📶 antenna bars
📳 vibration mode
📴 mobile phone off
♀️ female sign
♂️ male sign
⚕️ medical symbol
♾️ infinity
♻️ recycling symbol
⚜️ fleur-de-lis
🔱 trident emblem
📛 name badge
🔰 japanese symbol for beginner
⭕ red circle
✅ check mark button
☑️ check box with check
✔️ check mark
❌ cross mark
❎ cross mark button
➕ plus
➖ minus
➗ divide
➰ curly loop
➿ double curly loop
〽️ part alternation mark
✳️ eight-spoked asterisk
✴️ eight-pointed star
❇️ sparkle
‼️ double exclamation mark
⁉️ exclamation question mark
❓ question mark
❔ white question mark
❕ white exclamation mark
❗ exclamation mark
〰️ wavy dash
💱 currency exchange
💲 heavy dollar sign
⚕️ medical symbol
♻️ recycling symbol
⚜️ fleur-de-lis
🔱 trident emblem
📛 name badge
🔰 japanese symbol for beginner
⭕ red circle
✅ check mark button
☑️ check box with check
✔️ check mark
❌ cross mark
❎ cross mark button
➕ plus
➖ minus
➗ divide
➰ curly loop
➿ double curly loop
〽️ part alternation mark
✳️ eight-spoked asterisk
✴️ eight-pointed star
❇️ sparkle
‼️ double exclamation mark
⁉️ exclamation question mark
❓ question mark
❔ white question mark
❕ white exclamation mark
❗ exclamation mark
〰️ wavy dash
💱 currency exchange
💲 heavy dollar sign
🔟 keycap: 10
🔠 input latin uppercase
🔡 input latin lowercase
🔢 input numbers
🔣 input symbols
🔤 input latin letters
🅰️ a button (blood type)
🆎 ab button (blood type)
🅱️ b button (blood type)
🆑 cl button
🆒 cool button
🆓 free button
ℹ️ information
🆔 id button
Ⓜ️ circled m
🆕 new button
🆖 ng button
🅾️ o button (blood type)
🆗 ok button
🅿️ p button
🆘 sos button
🆙 up! button
🆚 vs button
🈁 japanese "here" button
🈂️ japanese "service charge" button
🈷️ japanese "monthly amount" button
🈶 japanese "not free of charge" button
🈯 japanese "reserved" button
🉐 japanese "bargain" button
🈹 japanese "discount" button
🈚 japanese "free of charge" button
🈲 japanese "prohibited" button
🉑 japanese "acceptable" button
🈸 japanese "application" button
🈴 japanese "passing grade" button
🈳 japanese "vacancy" button
㊗️ japanese "congratulations" button
㊙️ japanese "secret" button
🈺 japanese "open for business" button
🈵 japanese "no vacancy" button
🔴 red circle
🟠 orange circle
🟡 yellow circle
🟢 green circle
🔵 blue circle
🟣 purple circle
🟤 brown circle
⚫ black circle
⚪ white circle
🟥 red square
🟧 orange square
🟨 yellow square
🟩 green square
🟦 blue square
🟪 purple square
🟫 brown square
⬛ black large square
⬜ white large square
◼️ black medium square
◻️ white medium square
◾ black medium-small square
◽ white medium-small square
▪️ black small square
▫️ white small square
🔶 large orange diamond
🔷 large blue diamond
🔸 small orange diamond
🔹 small blue diamond
🔺 red triangle pointed up
🔻 red triangle pointed down
💠 diamond with a dot
🔘 radio button
🔳 white square button
🔲 black square button
